version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smartdocs-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ./backend/static/uploads:/app/static/uploads
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: smartdocs-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped
